### ISSUE TITLE
stop with the secret branches

### ISSUE THREAD

**Issue by gek169** [EscapeCharacter-dev/ModernStandard#1]
makes your stuff harder to look at why can't you just make normal repositories like a normal person instead of doing weird stuff to try to make everything you make hard to use

**Comment by EscapeCharacter-dev** [comment]
The latest version of the standard is now the default branch, meaning that you can pull and clone the latest version of the standard without needing to go do hunting for branches.

Old versions of the standard will be kept in other branches, but all new standards will include all of the old standards, so you don't have to go check the 2021.6 for basic language features.
